os:
- linux
sudo: false
language: node_js
rvm:
- "2.2.0"
node_js:
- "stable"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
  - $HOME/.gradle
before_install:
- java -version
- ruby --version
- gem --version
install:
- export CXX=g++-4.8
- bundle install --path vendor/bundle
- npm install
script:
- make test
- make html
- make pdf
- sh ./_tools/check-to-deploy.sh
after_success:
- rm .gitignore # ignore gitignore
- "./_tools/setup-git.sh"
- npm run build-js-min
- make deploy
env:
  global:
  - GH_REF: github.com/azu/promises-book.git
  - secure: pNtiVeWTe/kPWmERJURFoCVfzDVOc19IPbr9rK9CDJHo9aFtBPXkRwYzXfjlIwnzzkrAnfowxNNerHxYXuiNK7z+xNT9H79pmYtd1Qap9fNZCFNIFkdaArAXoq635VWmGRdArGiQGNM4Am+bZdsgG4dJR4DEsjx6dcisfyb8yso=
  - secure: Ne82o6v7wWwNQzd/2rKacyDgFgxLP822KPxxSZe/7/8gklbGMXOtDAhyW+5PgixOs7s3Vzknqw6dSTOPMY2c436F1ZJb6lMGcL6BPVSGmIXSYGm6C5SZIDTrp7QDarTAGCNiHlHFGySEhbz9R5CjPWF24kQfT/QdszZr7OokJYA=
branches:
  except:
    - preview-html
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/02e67e9b440eddb4a3da
    on_success: change
    on_failure: always
    on_start: false
