os:
  - linux
sudo: false
language: node_js
rvm:
  - 2.2.0
node_js:
  - stable
jdk: oraclejdk10
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - java -version
  - ruby --version
  - gem --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
install:
  - export JAVA_HOME=$HOME/openjdk12
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk12 --target $JAVA_HOME
  - export CXX=g++-4.8
  - bundle install --path vendor/bundle
  - yarn install
script:
  - make test
  - make html
  - make pdf
  - "./_tools/check-to-deploy.sh"
after_success:
  - "./_tools/setup-git.sh"
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - $(npm bin)/set-up-ssh --key "$encrypted_7b11bfc5945b_key" --iv "$encrypted_7b11bfc5945b_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - yarn run build-js-min
  - make deploy
env:
  global:
    - GH_REF: github.com/azu/promises-book.git
    - secure: pNtiVeWTe/kPWmERJURFoCVfzDVOc19IPbr9rK9CDJHo9aFtBPXkRwYzXfjlIwnzzkrAnfowxNNerHxYXuiNK7z+xNT9H79pmYtd1Qap9fNZCFNIFkdaArAXoq635VWmGRdArGiQGNM4Am+bZdsgG4dJR4DEsjx6dcisfyb8yso=
    - secure: Ne82o6v7wWwNQzd/2rKacyDgFgxLP822KPxxSZe/7/8gklbGMXOtDAhyW+5PgixOs7s3Vzknqw6dSTOPMY2c436F1ZJb6lMGcL6BPVSGmIXSYGm6C5SZIDTrp7QDarTAGCNiHlHFGySEhbz9R5CjPWF24kQfT/QdszZr7OokJYA=
